/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_journal_parsers_LastPageParser */

#ifndef _Included_com_example_journal_parsers_LastPageParser
#define _Included_com_example_journal_parsers_LastPageParser
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_journal_parsers_LastPageParser
 * Method:    parsePage
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_journal_parsers_LastPageParser_parsePage
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
